### ISSUE TITLE
Error when running :VimApm

### ISSUE THREAD

**Issue by ajongaro** [ThePrimeagen/vim-apm#16]
Error detected while processing function VimApm:
line    2:
E5108: Error executing lua vim/_editor.lua:0: Tried to call API function with vim.fn: use vim.api.nvim_win_get_width instead
stack traceback:
        [C]: in function 'error'
        vim/_editor.lua: in function 'nvim_win_get_width'
        ...o/.local/share/nvim/plugged/vim-apm/lua/vim-apm/init.lua:59: in function 'on_resize'
        ...o/.local/share/nvim/plugged/vim-apm/lua/vim-apm/init.lua:92: in function 'apm'
        [string ":lua"]:1: in main chunk

**Comment by aldevv** [comment]
@ThePrimeagen the plugin is broken

**Comment by ThePrimeagen** [comment]
i am closing this, apm is getting a revamp to become amazing
