### ISSUE TITLE
project dead?

### ISSUE THREAD

**Issue by tjdevries** [ThePrimeagen/vim-apm#20]
hey, i noticed no commits in the last 10 minutes. wondering if this project is dead?

**Comment by propbreakerfpv** [comment]
I think so. there isn't even a README

**Comment by tabre** [comment]
> I think so. there isn't even a README

I guess we have to read the code to figure out how to use it?

**Comment by trevarj** [comment]
I already reported this repository for being non-inclusive and abusive to slow typers. Hosting my own fork on sht.ht/vim-apm2

**Comment by Sarthak950** [comment]
The name is The Primeagen

**Comment by ThePrimeagen** [comment]
The name... is the Deadagen
