### ISSUE TITLE
All stats display 0

### ISSUE THREAD

**Issue by qoobes** [ThePrimeagen/vim-apm#22]
There isn't much more to it.

The previous version I had worked, but it had the "too many open files" problem which drove me mad cause I couldn't figure out what it was until it was fixed.

This one just shows this:

<img width="216" alt="image" src="https://github.com/ThePrimeagen/vim-apm/assets/58834655/84aba3a2-6898-4350-9c97-b8a37c6b9e4d">

My config (from the docs):

```lua
local apm = require("vim-apm")

apm:setup({})
vim.keymap.set("n", "<leader>apm", function()
	apm:toggle_monitor()
end)
```

**Comment by qoobes** [comment]
This makes me feel like a noob and deeply hurts my pride :'(

**Comment by Agent-E11** [comment]
I had this too, but then after a while (like maybe a minute) it started showing stats, so that might be the problem?

**Comment by qoobes** [comment]
Nah I don't think so, I've been using it for days as it's in the vim config I use for work. About to install the new version so wish me luck

**Comment by qoobes** [comment]
Okay, these new commits seem to have fixed the issue, although the stats update very slowly, but I guess that's something separate
