### ISSUE TITLE
Unknown option: kscb

### ISSUE THREAD

**Issue by iiison** [ThePrimeagen/vim-apm#4]
Hi, I have built Neovim from the [This PR](https://github.com/neovim/neovim/pull/12536). I followed the install instructions from the readme file. But I get an error saying `Unknown option: kscb`. I'm not sure what am I missing here.

**Comment by tjdevries** [comment]
The option no longer exists after the PR was updated.

Additionally, `id` is changed to `ns_id`, so you need to create it w/ `vim.api.nvim_create_namespace()`

**Comment by tjdevries** [comment]
(part 2 only possible via changes in the plugin)

**Comment by ThePrimeagen** [comment]
closing this as vim-apm is getting amazing revamp
