### ISSUE TITLE
Error while shutting down Vim Apm

### ISSUE THREAD

**Issue by smit2306** [ThePrimeagen/vim-apm#8]
Hi everyone,

I get below error when I try to shutdown the VimApm. 

Some information about NeoVIm and my Operating system. The same error is encountered in Ubuntu and MacOS both.

`
OS: MacOS Catalina 10.15.6 / Ubuntu 20.04`
`neovim version: 0.5.0-nightly` (installed using `brew install neovim --HEAD` command)

ERROR: 
`Error detected while processing function VimApmShutdown:
line    4:
E5108: Error executing lua /Users/smitpatel/.vim/plugged/vim-apm/lua/vim-apm/init.lua:40: attempt to call field 'remove_keystroke_callback' (a nil value)`
`'Press ENTER or type command to continue`

`Error executing vim.schedule lua callback: /Users/smitpatel/.vim/plugged/vim-apm/lua/vim-apm/init.lua:109: handle 0x7fe96c75a6e0 is already closing`
`Press ENTER or type command to continue`

`Error:  /Users/smitpatel/.vim/plugged/vim-apm/lua/vim-apm/init.lua:137: attempt to index global 'buckets' (a nil value)`
`Press ENTER or type command to continue`

`Error:  /Users/smitpatel/.vim/plugged/vim-apm/lua/vim-apm/init.lua:137: attempt to index global 'buckets' (a nil value)`
`Press ENTER or type command to continue`

**Comment by smit2306** [comment]
Hi @ThePrimeagen ,

Please look at line 40 in **_init.lua_** file.

`

    local function shutdown()
    if win_id ~= 0 then
        vim.fn.nvim_win_close(win_id, true)
    end

    if bufh ~= 0 then
        vim.cmd(string.format("bdelete! %s", bufh))
    end

    buckets = nil
    timerIdx = timerIdx + 1
    bufh = 0
    win_id = 0
    vim.remove_keystroke_callback(id) ----> CHECK THIS LINE
    active = false
     end
`

line 40: `vim.remove_keystroke_callback(id)` --> This is causing the error.

I looked up the Neovim lua api docs. There is no such function. 

I replaced this line of code with `vim.register_keystroke_callback(id)` and error is resolved.

I don't know if this is the correct solution, you guys would have a better idea on how to patch this more robustly.

**Comment by ThePrimeagen** [comment]
I'll look into this shortly!  

Sorry for not responding.  Missed the email.
